apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-ingress
  namespace: public-resources
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-public
  rules:
    - http:
        paths:
          - backend:
              service:
                name: temp2-service
                port:
                  number: 80
            path: /temp2
            pathType: Prefix
          - backend:
              service:
                name: temp3-service
                port:
                  number: 80
            path: /temp3
            pathType: Prefix
